import Navbar from './components/Navbar'
import './globals.css'
import Link from 'next/link'
export const metadata = {
  title: 'Businesss Template',
  description: 'Generated by younghun',
}


export default function RootLayout({ children }) {
  return (
    <html>
      
      <body>
      
      <header className=''>
      <Navbar />       
      </header>      
      <div className="w-screen bg-no-repeat bg-cover bg-[url('/server01.png')] h-[200px] xl:h-[500px]" >
      
        <div className="lg:container lg:mx-auto">
          <h1 className='text-center'>
            고객의 Business 성공과 함께 성장하는<br/>
            최고의 SI 전문 파트너
          </h1>
        </div>
      </div>

      <div>
        <div>
          <h3>시스템 구축 및 이전</h3>
          <p>임시 텍스트입니다</p>
        </div>
      </div>
      <div>
        <div>
          <h3>네트워크</h3>
          <p>임시 텍스트입니다</p>
        </div>
        <div>
          <h3>시스템 통합 유지보수</h3>
          <p>임시 텍스트입니다</p>
        </div>
        <div>
          <h3>네트워크</h3>
          <p>임시 텍스트입니다</p>
        </div>
      </div>
      <div>
        시스템 구축 
      </div>
      <div>
        <ul className='flex'>
          <li>회사소개</li>
          <li>파트너</li>
          <li>Contact Us</li>
          <li>오시는 길</li>
        </ul>
      </div>
      {children}      
      <footer className='bg-gray-800 text-gray-400'>
        <h4>(주) 이룸인프라</h4>
        <address>
        <ul>
          <li><a href='tel:02-857-7008'>TEL:02-857-7008</a></li>
          <li>대표:정명호</li>
          <li><a href='mailto:mhjung@iruminfra.co.kr'>e-Mail:mhjung@iruminfra.co.kr</a></li>
          <li><a target="_blank" rel="noreferrer" href="https://map.naver.com/v5/search/%EC%84%9C%EC%9A%B8%EC%8B%9C%20%EA%B5%AC%EB%A1%9C%EA%B5%AC%20%EB%94%94%EC%A7%80%ED%84%B8%EB%A1%9C%2033%EA%B8%B8%2012%20%EC%9A%B0%EB%A6%BC%20E-Biz%EC%84%BC%ED%84%B0%202%EC%B0%A8%20707%ED%98%B8/address/14126015.89255784,4507147.929730302,%EC%84%9C%EC%9A%B8%ED%8A%B9%EB%B3%84%EC%8B%9C%20%EA%B5%AC%EB%A1%9C%EA%B5%AC%20%EB%94%94%EC%A7%80%ED%84%B8%EB%A1%9C33%EA%B8%B8%2012,new?c=14125951.9283784,4507137.7306574,18,0,0,0,dh">주소:서울시 구로구 디지털로 33길 12 우림 E-Biz센터 2차 612호</a></li>
        </ul>
        </address>
      </footer>
      </body>
    </html>
  )
}
